### PR TITLE
fix(state-transfer): correct http post & patch method params

### PR DESCRIPTION
**Pull request by MoLow**
** PR Checklist
Please check if your PR fulfills the following requirements:

- [X] The commit message follows our guidelines: https://github.com/fulls1z3/ngx-universal/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

** PR Type
What kind of change does this PR introduce?

```
[X] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

** What is the current behavior?

Issue Number: N/A

** What is the new behavior?
http Post works now

** Does this PR introduce a breaking change?
```
[ ] Yes
[X] No
```

** Other information

### CODE REVIEW

**Comment by fulls1z3** [comment]
@MoLow I really appreciate your attention to these details, awesome job 👍

**Comment by MoLow** [comment]
@fulls1z3 when would this be published to npm? I have a production error

**Comment by fulls1z3** [comment]
@MoLow done, give it a try and let me know about the results.

**Comment by MoLow** [comment]
works. thanks!

**Comment by fulls1z3** [comment]
@MoLow thanks too, for pointing out and quickly fixing the issue 👍

**Pull request merged**
